### ISSUE TITLE
Migrating src code to ES6

### ISSUE THREAD

**Issue by iFlameing** [processing/p5.js-sound#345]
I am working on it :)

**Comment by therewasaguy** [comment]
Thank you for starting on this, @iFlameing !

I suggest we break this down into smaller issues.

Some pieces that come to mind:
1. [upgrade build tools as needed so that we can use ES6+ conventions in source code](https://github.com/processing/p5.js-sound/issues/348
) (https://github.com/processing/p5.js-sound/issues/348)

2. favor `let` and `const` (as appropriate) over `var` (as you've started here https://github.com/processing/p5.js-sound/pull/347)

3. favor `class` over the function prototype approach to creating classes
*#348 needs to happen first, we currently get this error
```
Running "requirejs:unmin" (requirejs) task
{ Error: Error: Line 40: Unexpected reserved word
    at throwError (/Users/jasonsigal/src/p5/p5.js-sound/node_modules/esprima/esprima.js:1846:21)

    at /Users/jasonsigal/src/p5/p5.js-sound/node_modules/requirejs/bin/r.js:30099:19
```

**Comment by iFlameing** [comment]
@therewasaguy can you provide me an example code of the class. so that I can reproduce this issue regarding the class.
