### ISSUE TITLE
upgrade build tools so that we can use ES6+ conventions in source code

### ISSUE THREAD

**Issue by therewasaguy** [processing/p5.js-sound#348]

**Comment by iFlameing** [comment]
@therewasaguy I think we have to solve this before going to convert the src code to es6. what do you think?

**Comment by iFlameing** [comment]
@therewasaguy I found a blog for converting the es6 to es5. would you take a look.

**Comment by iFlameing** [comment]
@therewasaguy can you tell me how I can reproduce this behavior
```
Running "requirejs:unmin" (requirejs) task
{ Error: Error: Line 40: Unexpected reserved word
    at throwError (/Users/jasonsigal/src/p5/p5.js-sound/node_modules/esprima/esprima.js:1846:21)

    at /Users/jasonsigal/src/p5/p5.js-sound/node_modules/requirejs/bin/r.js:30099:19 
```
Can you provide me some sample code for this?
