### ISSUE TITLE
p5.PolySynth example returns error

### ISSUE THREAD

**Issue by mattshu** [processing/p5.js-sound#656]
**Actual Behaviour**

Browsing the p5.PolySynth docs and attempted to use the provided example object `click to play`

 **Expected Behaviour**

A music chord should play

 **Steps to reproduce it**

 CLick the `click to play` box

 **Screenshots of the issue**

This is what shows in the console upon loading:
```
The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. <URL>
index.js:569 Uncaught TypeError: Cannot read properties of undefined (reading 'colorScheme')
    at index.js:569:25
    at index.js:570:7
    at index.js:6165:3
(anonymous) @ index.js:569
(anonymous) @ index.js:570
(anonymous) @ index.js:6165
frame.js:1 Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')
    at frame.js:1:15
(anonymous) @ frame.js:1
DevTools failed to load source map: Could not load content for https://p5js.org/assets/js/p5.sound.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```
This happens when pressing the object:
```
p5.sound.min.js?v=f067ef:2 Uncaught ReferenceError: oldestNote is not defined
    at n.value (p5.sound.min.js?v=f067ef:2:194994)
    at n.value (p5.sound.min.js?v=f067ef:2:194331)
    at d.default.Renderer2D.playSynth (eval at s (render.js?v=b98ef7:241:13), <anonymous>:26:13)
    at d.default.Renderer2D.<anonymous> (p5.min.js?v=3af01e:3:435211)
```

 **Would you like to work on the issue?**

I would if I knew how :(

**Comment by rinkydevi** [comment]
hey @mattshu i would love to work on this issue

**Comment by filipesabella** [comment]
I'm seeing the same issue, on Firefox and Edge, when there are too many notes played in a short interval.

For example (apologies for the messy code):
https://editor.p5js.org/fs_/sketches/EssUnKJ2Q

If you increase the amount of notes played by uncommenting line 9 ( `scale = [...scale, ...scale];`) and press play, the exception `oldestNote is not defined` is thrown.

Oddly enough, running this same code inside electron does not cause this exception.

**Comment by D17124399** [comment]
I am getting this error in P5js today. Are there any updates on oldestNote issue? Thanks.

**Comment by ffd8** [comment]
Eeek, running into this as well – though I am testing in a strange context (live coding, where code is sometimes recompiled, sometimes not...) – found that if I cause an error in the code, fix it, recompile – i get this error of 'oldestNote is not defined' – the error must be somewhere [around here](https://github.com/processing/p5.js/blob/v1.6.0/lib/addons/p5.sound.js#L11969).  Perhaps it's because it's being created without a var/let or needs to have a fallback incase it produces a bad value?

**Comment by Steve-Tech** [comment]
I also got `Uncaught ReferenceError: assignment to undeclared variable oldestNote` at `p5.sound.js:11969:24` in Firefox.

But it looks to be fixed by commit https://github.com/processing/p5.js-sound/commit/1db3db8666f86bb2e88aa98a3261e00f5a9f7ef9 and I don't have the error in [v1.0.2](https://github.com/processing/p5.js-sound/releases/tag/v1.0.2) (releases are inside the [lib](https://github.com/processing/p5.js-sound/tree/main/lib) folder).

Additionally adding `let` in front of the first `oldestNote` fixes the issue if you can't use a newer version.
